version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  analysis:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Dependencies
          command: sudo apt update && sudo apt install -y libbluetooth-dev
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run analysis
          command: poetry run task lint
      - store_test_results:
          path: analysis_results.xml
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Dependencies
          command: sudo apt update && sudo apt install -y libbluetooth-dev
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run test
          command: poetry run task test
      - store_test_results:
          path: test_results.xml
      - store_artifacts:
          path: htmlcov
  publish:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Publish
          command:
            poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD

workflows:
  unit_test:
    jobs:
      - analysis:
          filters: &filters-test
            tags:
              ignore: /.*/
      - test:
          filters:
            <<: *filters-test
  deploy:
    jobs:
      - publish:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
